## Enviornment configurations
accessionList = "00-helperfiles/Angel_accList.txt"
database = "rdp_16s_v16.fa"

## Output directories
workspace = "/Snake/Angel/"
sampleDir = "/01-rawData/Angel/"
adapterOut = workspace + "02-adapters/"
mergeOut = workspace + "03-merge/"
primerOut = workspace + "04-primers/" 
filterOut = workspace + "05-filtering/"
poolOut = workspace + "06-pool/"
dereplicateOut = workspace + "07-dereplicate/"
ASVsOut = workspace + "08-ASVs/"

## Required lists
samples = []
reads = ["1", "2"]

## Making a list of samples
with open(accessionList) as f:
    for line in f:
        sample_full = line.split("\n")
        samples.append(sample_full[0])

rule all:
    input:
        ASVsOut + "zouts.fasta",
        ASVsOut + "zotutab_raw.txt",
        ASVsOut + "distmx.txt",
        ASVsOut + "zotus.tree",
        ASVsOut + "sintax.txt"

rule adapter_removal:
    input:
        forwardIn = sampleDir + "{samples}_1.fastq",
        reverseIn = sampleDir + "{samples}_2.fastq"
    output:
        forwardOut = temporary(adapterOut + "{samples}_noAda_1.fastq"),
        reverseOut = temporary(adapterOut + "{samples}_noAda_2.fastq")
    threads: 4
    message: "Removing universal adapters using bbduk"
    shell:
        """
        bbduk.sh in1={input.forwardIn} in2={input.reverseIn} \
        out1={output.forwardOut} out2={output.reverseOut} \
        ref=adapters hdist=1 tpe tbo
        """

rule merge:
    input: 
        forwardIn = adapterOut + "{samples}_noAda_1.fastq",
        reverseIn = adapterOut + "{samples}_noAda_2.fastq"
    output:
        mergedOut = temporary(mergeOut + "{samples}.fastq")
    params:
        sampleName = "{samples}"
    threads: 4
    message: "Merging reads"
    shell:
        """
        /home/ddodani/bin/usearch11.0.667_i86linux32 -fastq_mergepairs {input.forwardIn} -reverse {input.reverseIn} \
        -fastqout {output.mergedOut} -relabel {params.sampleName}. \
        -fastq_minmergelen 400
        """

rule primer_removal:
    input:
        readIn = mergeOut + "{samples}.fastq"
    output:
        readOut = temporary(primerOut + "{samples}.fastq")
    threads: 4
    message: "Removal of primers using userach"
    shell:
        """
        /home/ddodani/bin/usearch11.0.667_i86linux32 \
        -fastx_truncate {input.readIn} -stripleft 55 -stripright 55 \
        -fastqout {output.readOut}
        """

rule quality_filtering:
    input:
        readIn = primerOut + "{samples}.fastq"
    output:
        readOut = temporary(filterOut + "{samples}.fasta")
    threads: 4
    message: "Quality filtering using usearch"
    params:
        sampleName = "{samples}"
    shell:
        """
            /home/ddodani/bin/usearch11.0.667_i86linux32 \
            -fastq_filter {input.readIn} -fastq_maxee 1.0 -relabel {params.sampleName}. \
            -fastaout {output.readOut}
        """

rule pool_samples:
    input: 
        reads = expand(filterOut + "{samples}.fasta", samples=samples)
    output:
        readsOut = poolOut + "all_merged.fasta"
    threads: 4
    message: "Pooling samples"
    shell:
        """
        cat {input.reads} > {output.readsOut} 
        """

rule dereplicate:
    input:
        readsIn = poolOut + "all_merged.fasta"
    output:
        readsOut = dereplicateOut + "uniques.fasta"
    threads: 4
    message: "Dereplicating samples for faster computation"
    shell:
        """
        /home/ddodani/bin/usearch11.0.667_i86linux32 \
            -fastx_uniques {input.readsIn} \
            -sizeout -relabel Uniq \
            -fastaout {output.readsOut}
        """

rule cluster_ASVs:
    input:
        readsIn = dereplicateOut + "uniques.fasta",
        mergedIn = poolOut + "all_merged.fasta"
    output:
        asvsFasta = ASVsOut + "zouts.fasta",
        asvtab = ASVsOut + "zotutab_raw.txt",
        dismat = ASVsOut + "distmx.txt",
        tree = ASVsOut + "zotus.tree",
        sintaxOut = ASVsOut + "sintax.txt"
    threads: 4
    message: "Clustering reads into ASVs"
    params:
        datab = database
        adapterDir = adapterOut,
        mergeDir = mergeOut,
        primerDir = primerOut,
        filterDir = filterOut,
        poolDir = poolOut,
        dereplicateDir = dereplicateOut,
        asvsDir = ASVsOut
    shell:
        """
        /home/ddodani/bin/usearch11.0.667_i86linux32 -unoise3 {input.readsIn} -zotus {output.asvsFasta}
        
        /home/ddodani/bin/usearch11.0.667_i86linux32 -otutab {input.mergedIn} -otus {output.asvsFasta} -otutabout {output.asvtab}

        /home/ddodani/bin/usearch11.0.667_i86linux32 -calc_distmx {output.asvsFasta} -tabbedout {output.dismat}

        /home/ddodani/bin/usearch11.0.667_i86linux32 -cluster_aggd {output.dismat} -treeout {output.tree}

        /home/ddodani/bin/usearch11.0.667_i86linux32 -sintax {output.asvsFasta} -db {params.datab} -strand both -tabbedout {output.sintaxOut} -sintax_cutoff 0.8

        rm -r {params.adapterDir} {params.mergeDir} {params.primerDir} {params.filterDir} {params.poolDir} {params.dereplicateDir}
        """